(cl:in-package darknet_msgs-msg)
(cl:export '(E_CUV-VAL
          E_CUV
          E_RIV-VAL
          E_RIV
          E_WHV-VAL
          E_WHV
          E_COV-VAL
          E_COV
          D_CUV-VAL
          D_CUV
          D_RIV-VAL
          D_RIV
          D_WHV-VAL
          D_WHV
          D_COV-VAL
          D_COV
          C_CUV-VAL
          C_CUV
          C_RIV-VAL
          C_RIV
          C_WHV-VAL
          C_WHV
          C_COV-VAL
          C_COV
          B_CUV-VAL
          B_CUV
          B_RIV-VAL
          B_RIV
          B_WHV-VAL
          B_WHV
          B_COV-VAL
          B_COV
          F_CUF-VAL
          F_CUF
          F_COF-VAL
          F_COF
          F_WAF-VAL
          F_WAF
))