// Generated by gencpp from file sr_pkg/get_pose.msg
// DO NOT EDIT!


#ifndef SR_PKG_MESSAGE_GET_POSE_H
#define SR_PKG_MESSAGE_GET_POSE_H

#include <ros/service_traits.h>


#include <sr_pkg/get_poseRequest.h>
#include <sr_pkg/get_poseResponse.h>


namespace sr_pkg
{

struct get_pose
{

typedef get_poseRequest Request;
typedef get_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_pose
} // namespace sr_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sr_pkg::get_pose > {
  static const char* value()
  {
    return "2e9083aa4360091925401acb66844bd2";
  }

  static const char* value(const ::sr_pkg::get_pose&) { return value(); }
};

template<>
struct DataType< ::sr_pkg::get_pose > {
  static const char* value()
  {
    return "sr_pkg/get_pose";
  }

  static const char* value(const ::sr_pkg::get_pose&) { return value(); }
};


// service_traits::MD5Sum< ::sr_pkg::get_poseRequest> should match
// service_traits::MD5Sum< ::sr_pkg::get_pose >
template<>
struct MD5Sum< ::sr_pkg::get_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sr_pkg::get_pose >::value();
  }
  static const char* value(const ::sr_pkg::get_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_pkg::get_poseRequest> should match
// service_traits::DataType< ::sr_pkg::get_pose >
template<>
struct DataType< ::sr_pkg::get_poseRequest>
{
  static const char* value()
  {
    return DataType< ::sr_pkg::get_pose >::value();
  }
  static const char* value(const ::sr_pkg::get_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sr_pkg::get_poseResponse> should match
// service_traits::MD5Sum< ::sr_pkg::get_pose >
template<>
struct MD5Sum< ::sr_pkg::get_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sr_pkg::get_pose >::value();
  }
  static const char* value(const ::sr_pkg::get_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sr_pkg::get_poseResponse> should match
// service_traits::DataType< ::sr_pkg::get_pose >
template<>
struct DataType< ::sr_pkg::get_poseResponse>
{
  static const char* value()
  {
    return DataType< ::sr_pkg::get_pose >::value();
  }
  static const char* value(const ::sr_pkg::get_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SR_PKG_MESSAGE_GET_POSE_H
